In [ ]:
import pandas as pd
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import re

In [ ]:
a1 = pd.read_csv('/content/a1_RestaurantReviews_HistoricDump.tsv', sep = '\t')
a1

                                                Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
895  I want to first say our server was great and w...      1
896                     The pizza selections are good.      1
897              I had strawberry tea, which was good.      1
898  Highly unprofessional and rude to a loyal patron!      0
899                       Overall, a great experience.      1

[900 rows x 2 columns]

# **Text Blob**

In [ ]:
!pip install textblob

Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in /usr/local/lib/python3.12/dist-packages (from textblob) (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (8.4.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (4.67.3)

In [ ]:
from textblob import TextBlob

a1['TextBlob_Polarity'] = a1['Review'].apply(
    lambda x: TextBlob(str(x)).sentiment.polarity
)

a1['TextBlob_Subjectivity'] = a1['Review'].apply(
    lambda x: TextBlob(str(x)).sentiment.subjectivity
)

In [ ]:
def textblob_sentiment(score):
    if score > 0:
        return 'Positive'
    elif score < 0:
        return 'Negative'
    else:
        return 'Neutral'

a1['TextBlob_Sentiment'] = a1['TextBlob_Polarity'].apply(textblob_sentiment)

<function textblob_sentiment at 0x7e40059f2b60>

In [ ]:
a1[['Review', 'Liked', 'TextBlob_Polarity',
    'TextBlob_Subjectivity', 'TextBlob_Sentiment']].head(20)

,Review,Liked,TextBlob_Polarity,TextBlob_Subjectivity,TextBlob_Sentiment
0,Wow... Loved this place.,1,0.40000,0.900000,Positive
1,Crust is not good.,0,-0.35000,0.600000,Negative
2,Not tasty and the texture was just nasty.,0,-1.00000,1.000000,Negative
3,Stopped by during the late May bank holiday of...,1,0.20000,0.700000,Positive
4,The selection on the menu was great and so wer...,1,0.80000,0.750000,Positive
5,Now I am getting angry and I want my damn pho.,0,-0.50000,1.000000,Negative
6,Honeslty it didn't taste THAT fresh.),0,0.30000,0.500000,Positive
7,The potatoes were like rubber and you could te...,0,0.00000,0.000000,Neutral
8,The fries were great too.,1,0.80000,0.750000,Positive
9,A great touch.,1,0.80000,0.750000,Positive
10,Service was very prompt.,1,0.20000,0.300000,Positive
11,Would not go back.,0,0.00000,0.000000,Neutral
12,The cashier had no care what so ever on what I...,0,0.00000,0.000000,Neutral
13,"I tried the Cape Cod ravoli, chicken, with cra...",1,-0.75000,0.950000,Negative
14,I was disgusted because I was pretty sure that...,0,-0.06250,0.747222,Negative
15,I was shocked because no signs indicate cash o...,0,-0.35000,0.900000,Negative
16,Highly recommended.,1,0.16000,0.540000,Positive
17,Waitress was a little slow in service.,0,-0.24375,0.450000,Negative
18,"This place is not worth your time, let alone V...",0,-0.15000,0.100000,Negative
19,did not like at all.,0,0.00000,0.000000,Neutral

# **Sentiment Analyzer**

In [ ]:
import nltk

nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

True

In [ ]:
from nltk.sentiment import SentimentIntensityAnalyzer

sia = SentimentIntensityAnalyzer()

a1['VADER_Score'] = a1['Review'].apply(
    lambda x: sia.polarity_scores(str(x))['compound']
)

def vader_sentiment(score):
    if score >= 0.05:
        return 'Positive'
    elif score <= -0.05:
        return 'Negative'
    else:
        return 'Neutral'

a1['VADER_Sentiment'] = a1['VADER_Score'].apply(vader_sentiment)

In [ ]:
a1[['Review', 'Liked', 'VADER_Score', 'VADER_Sentiment']].head(20)

,Review,Liked,VADER_Score,VADER_Sentiment
0,Wow... Loved this place.,1,0.5994,Positive
1,Crust is not good.,0,-0.3412,Negative
2,Not tasty and the texture was just nasty.,0,-0.5574,Negative
3,Stopped by during the late May bank holiday of...,1,0.6908,Positive
4,The selection on the menu was great and so wer...,1,0.6249,Positive
5,Now I am getting angry and I want my damn pho.,0,-0.6908,Negative
6,Honeslty it didn't taste THAT fresh.),0,0.0000,Neutral
7,The potatoes were like rubber and you could te...,0,0.5719,Positive
8,The fries were great too.,1,0.6249,Positive
9,A great touch.,1,0.6249,Positive
10,Service was very prompt.,1,0.0000,Neutral
11,Would not go back.,0,0.0000,Neutral
12,The cashier had no care what so ever on what I...,0,0.2500,Positive
13,"I tried the Cape Cod ravoli, chicken, with cra...",1,0.0000,Neutral
14,I was disgusted because I was pretty sure that...,0,0.2732,Positive
15,I was shocked because no signs indicate cash o...,0,-0.5423,Negative
16,Highly recommended.,1,0.2716,Positive
17,Waitress was a little slow in service.,0,0.0000,Neutral
18,"This place is not worth your time, let alone V...",0,-0.3952,Negative
19,did not like at all.,0,-0.2755,Negative

# **Hugging Face**

In [ ]:
!pip install transformers torch

from transformers import pipeline

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.13.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.11.0+cpu)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.23.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.29.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

In [ ]:
hf_sentiment = pipeline("sentiment-analysis")

review = a1['Review'][0]

result = hf_sentiment(review)

print(review)
print(result)

a1['HF_Result'] = a1['Review'].head(10).apply(
    lambda x: hf_sentiment(str(x))[0]
)

a1[['Review', 'Liked', 'HF_Result']].head(10)

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Wow... Loved this place.
[{'label': 'POSITIVE', 'score': 0.9998804330825806}]

,Review,Liked,HF_Result
0,Wow... Loved this place.,1,"{'label': 'POSITIVE', 'score': 0.9998804330825..."
1,Crust is not good.,0,"{'label': 'NEGATIVE', 'score': 0.9997690320014..."
2,Not tasty and the texture was just nasty.,0,"{'label': 'NEGATIVE', 'score': 0.9996275901794..."
3,Stopped by during the late May bank holiday of...,1,"{'label': 'POSITIVE', 'score': 0.9995303153991..."
4,The selection on the menu was great and so wer...,1,"{'label': 'POSITIVE', 'score': 0.9996086955070..."
5,Now I am getting angry and I want my damn pho.,0,"{'label': 'NEGATIVE', 'score': 0.992295503616333}"
6,Honeslty it didn't taste THAT fresh.),0,"{'label': 'NEGATIVE', 'score': 0.9909782409667..."
7,The potatoes were like rubber and you could te...,0,"{'label': 'NEGATIVE', 'score': 0.9024147391319..."
8,The fries were great too.,1,"{'label': 'POSITIVE', 'score': 0.9997226595878..."
9,A great touch.,1,"{'label': 'POSITIVE', 'score': 0.9998835325241..."

In [ ]:
hf_results = hf_sentiment(
    a1['Review'].astype(str).tolist(),
    truncation=True
)

a1['HF_Sentiment'] = [result['label'] for result in hf_results]

a1['HF_Score'] = [result['score'] for result in hf_results]

a1[['Review', 'Liked', 'HF_Sentiment', 'HF_Score']].head(20)

,Review,Liked,HF_Sentiment,HF_Score
0,Wow... Loved this place.,1,POSITIVE,0.999880
1,Crust is not good.,0,NEGATIVE,0.999769
2,Not tasty and the texture was just nasty.,0,NEGATIVE,0.999628
3,Stopped by during the late May bank holiday of...,1,POSITIVE,0.999530
4,The selection on the menu was great and so wer...,1,POSITIVE,0.999609
5,Now I am getting angry and I want my damn pho.,0,NEGATIVE,0.992296
6,Honeslty it didn't taste THAT fresh.),0,NEGATIVE,0.990978
7,The potatoes were like rubber and you could te...,0,NEGATIVE,0.902415
8,The fries were great too.,1,POSITIVE,0.999723
9,A great touch.,1,POSITIVE,0.999884
10,Service was very prompt.,1,POSITIVE,0.996283
11,Would not go back.,0,NEGATIVE,0.997835
12,The cashier had no care what so ever on what I...,0,NEGATIVE,0.999760
13,"I tried the Cape Cod ravoli, chicken, with cra...",1,NEGATIVE,0.976239
14,I was disgusted because I was pretty sure that...,0,NEGATIVE,0.999424
15,I was shocked because no signs indicate cash o...,0,NEGATIVE,0.997476
16,Highly recommended.,1,POSITIVE,0.999844
17,Waitress was a little slow in service.,0,NEGATIVE,0.999520
18,"This place is not worth your time, let alone V...",0,NEGATIVE,0.999808
19,did not like at all.,0,NEGATIVE,0.996615

In [ ]:
a1[['Review',
    'Liked',
    'TextBlob_Sentiment',
    'VADER_Sentiment',
    'HF_Sentiment']].head(20)

,Review,Liked,TextBlob_Sentiment,VADER_Sentiment,HF_Sentiment
0,Wow... Loved this place.,1,Positive,Positive,POSITIVE
1,Crust is not good.,0,Negative,Negative,NEGATIVE
2,Not tasty and the texture was just nasty.,0,Negative,Negative,NEGATIVE
3,Stopped by during the late May bank holiday of...,1,Positive,Positive,POSITIVE
4,The selection on the menu was great and so wer...,1,Positive,Positive,POSITIVE
5,Now I am getting angry and I want my damn pho.,0,Negative,Negative,NEGATIVE
6,Honeslty it didn't taste THAT fresh.),0,Positive,Neutral,NEGATIVE
7,The potatoes were like rubber and you could te...,0,Neutral,Positive,NEGATIVE
8,The fries were great too.,1,Positive,Positive,POSITIVE
9,A great touch.,1,Positive,Positive,POSITIVE
10,Service was very prompt.,1,Positive,Neutral,POSITIVE
11,Would not go back.,0,Neutral,Neutral,NEGATIVE
12,The cashier had no care what so ever on what I...,0,Neutral,Positive,NEGATIVE
13,"I tried the Cape Cod ravoli, chicken, with cra...",1,Negative,Neutral,NEGATIVE
14,I was disgusted because I was pretty sure that...,0,Negative,Positive,NEGATIVE
15,I was shocked because no signs indicate cash o...,0,Negative,Negative,NEGATIVE
16,Highly recommended.,1,Positive,Positive,POSITIVE
17,Waitress was a little slow in service.,0,Negative,Neutral,NEGATIVE
18,"This place is not worth your time, let alone V...",0,Negative,Negative,NEGATIVE
19,did not like at all.,0,Neutral,Negative,NEGATIVE

In [ ]:
ps = PorterStemmer()

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
corpus = []
for i in range(0, len(a1)):
  review = re.sub('[^a-zA-Z]', ' ', a1['Review'][i])
  review = review.lower()
  review = review.split()
  print(review)
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  print(review)
  corpus.append(review)

['wow', 'loved', 'this', 'place']
wow love place
['crust', 'is', 'not', 'good']
crust good
['not', 'tasty', 'and', 'the', 'texture', 'was', 'just', 'nasty']
tasti textur nasti
['stopped', 'by', 'during', 'the', 'late', 'may', 'bank', 'holiday', 'off', 'rick', 'steve', 'recommendation', 'and', 'loved', 'it']
stop late may bank holiday rick steve recommend love
['the', 'selection', 'on', 'the', 'menu', 'was', 'great', 'and', 'so', 'were', 'the', 'prices']
select menu great price
['now', 'i', 'am', 'getting', 'angry', 'and', 'i', 'want', 'my', 'damn', 'pho']
get angri want damn pho
['honeslty', 'it', 'didn', 't', 'taste', 'that', 'fresh']
honeslti tast fresh
['the', 'potatoes', 'were', 'like', 'rubber', 'and', 'you', 'could', 'tell', 'they', 'had', 'been', 'made', 'up', 'ahead', 'of', 'time', 'being', 'kept', 'under', 'a', 'warmer']
potato like rubber could tell made ahead time kept warmer
['the', 'fries', 'were', 'great', 'too']
fri great
['a', 'great', 'touch']
great touch
['service', 'was', 'very', 'prompt']
servic prompt
['would', 'not', 'go', 'back']
would go back
['the', 'cashier', 'had', 'no', 'care', 'what', 'so', 'ever', 'on', 'what', 'i', 'had', 'to', 'say', 'it', 'still', 'ended', 'up', 'being', 'wayyy', 'overpriced']
cashier care ever say still end wayyy overpr
['i', 'tried', 'the', 'cape', 'cod', 'ravoli', 'chicken', 'with', 'cranberry', 'mmmm']
tri cape cod ravoli chicken cranberri mmmm
['i', 'was', 'disgusted', 'because', 'i', 'was', 'pretty', 'sure', 'that', 'was', 'human', 'hair']
disgust pretti sure human hair
['i', 'was', 'shocked', 'because', 'no', 'signs', 'indicate', 'cash', 'only']
shock sign indic cash
['highly', 'recommended']
highli recommend
['waitress', 'was', 'a', 'little', 'slow', 'in', 'service']
waitress littl slow servic
['this', 'place', 'is', 'not', 'worth', 'your', 'time', 'let', 'alone', 'vegas']
place worth time let alon vega
['did', 'not', 'like', 'at', 'all']
like
['the', 'burrittos', 'blah']
burritto blah
['the', 'food', 'amazing']
food amaz
['service', 'is', 'also', 'cute']
servic also cute
['i', 'could', 'care', 'less', 'the', 'interior', 'is', 'just', 'beautiful']
could care less interior beauti
['so', 'they', 'performed']
perform
['that', 's', 'right', 'the', 'red', 'velvet', 'cake', 'ohhh', 'this', 'stuff', 'is', 'so', 'good']
right red velvet cake ohhh stuff good
['they', 'never', 'brought', 'a', 'salad', 'we', 'asked', 'for']
never brought salad ask
['this', 'hole', 'in', 'the', 'wall', 'has', 'great', 'mexican', 'street', 'tacos', 'and', 'friendly', 'staff']
hole wall great mexican street taco friendli staff
['took', 'an', 'hour', 'to', 'get', 'our', 'food', 'only', 'tables', 'in', 'restaurant', 'my', 'food', 'was', 'luke', 'warm', 'our', 'sever', 'was', 'running', 'around', 'like', 'he', 'was', 'totally', 'overwhelmed']
took hour get food tabl restaur food luke warm sever run around like total overwhelm
['the', 'worst', 'was', 'the', 'salmon', 'sashimi']
worst salmon sashimi
['also', 'there', 'are', 'combos', 'like', 'a', 'burger', 'fries', 'and', 'beer', 'for', 'which', 'is', 'a', 'decent', 'deal']
also combo like burger fri beer decent deal
['this', 'was', 'like', 'the', 'final', 'blow']
like final blow
['i', 'found', 'this', 'place', 'by', 'accident', 'and', 'i', 'could', 'not', 'be', 'happier']
found place accid could happier
['seems', 'like', 'a', 'good', 'quick', 'place', 'to', 'grab', 'a', 'bite', 'of', 'some', 'familiar', 'pub', 'food', 'but', 'do', 'yourself', 'a', 'favor', 'and', 'look', 'elsewhere']
seem like good quick place grab bite familiar pub food favor look elsewher
['overall', 'i', 'like', 'this', 'place', 'a', 'lot']
overal like place lot
['the', 'only', 'redeeming', 'quality', 'of', 'the', 'restaurant', 'was', 'that', 'it', 'was', 'very', 'inexpensive']
redeem qualiti restaur inexpens
['ample', 'portions', 'and', 'good', 'prices']
ampl portion good price
['poor', 'service', 'the', 'waiter', 'made', 'me', 'feel', 'like', 'i', 'was', 'stupid', 'every', 'time', 'he', 'came', 'to', 'the', 'table']
poor servic waiter made feel like stupid everi time came tabl
['my', 'first', 'visit', 'to', 'hiro', 'was', 'a', 'delight']
first visit hiro delight
['service', 'sucks']
servic suck
['the', 'shrimp', 'tender', 'and', 'moist']
shrimp tender moist
['there', 'is', 'not', 'a', 'deal', 'good', 'enough', 'that', 'would', 'drag', 'me', 'into', 'that', 'establishment', 'again']
deal good enough would drag establish
['hard', 'to', 'judge', 'whether', 'these', 'sides', 'were', 'good', 'because', 'we', 'were', 'grossed', 'out', 'by', 'the', 'melted', 'styrofoam', 'and', 'didn', 't', 'want', 'to', 'eat', 'it', 'for', 'fear', 'of', 'getting', 'sick']
hard judg whether side good gross melt styrofoam want eat fear get sick
['on', 'a', 'positive', 'note', 'our', 'server', 'was', 'very', 'attentive', 'and', 'provided', 'great', 'service']
posit note server attent provid great servic
['frozen', 'pucks', 'of', 'disgust', 'with', 'some', 'of', 'the', 'worst', 'people', 'behind', 'the', 'register']
frozen puck disgust worst peopl behind regist
['the', 'only', 'thing', 'i', 'did', 'like', 'was', 'the', 'prime', 'rib', 'and', 'dessert', 'section']
thing like prime rib dessert section
['it', 's', 'too', 'bad', 'the', 'food', 'is', 'so', 'damn', 'generic']
bad food damn gener
['the', 'burger', 'is', 'good', 'beef', 'cooked', 'just', 'right']
burger good beef cook right
['if', 'you', 'want', 'a', 'sandwich', 'just', 'go', 'to', 'any', 'firehouse']
want sandwich go firehous
['my', 'side', 'greek', 'salad', 'with', 'the', 'greek', 'dressing', 'was', 'so', 'tasty', 'and', 'the', 'pita', 'and', 'hummus', 'was', 'very', 'refreshing']
side greek salad greek dress tasti pita hummu refresh
['we', 'ordered', 'the', 'duck', 'rare', 'and', 'it', 'was', 'pink', 'and', 'tender', 'on', 'the', 'inside', 'with', 'a', 'nice', 'char', 'on', 'the', 'outside']
order duck rare pink tender insid nice char outsid
['he', 'came', 'running', 'after', 'us', 'when', 'he', 'realized', 'my', 'husband', 'had', 'left', 'his', 'sunglasses', 'on', 'the', 'table']
came run us realiz husband left sunglass tabl
['their', 'chow', 'mein', 'is', 'so', 'good']
chow mein good
['they', 'have', 'horrible', 'attitudes', 'towards', 'customers', 'and', 'talk', 'down', 'to', 'each', 'one', 'when', 'customers', 'don', 't', 'enjoy', 'their', 'food']
horribl attitud toward custom talk one custom enjoy food
['the', 'portion', 'was', 'huge']
portion huge
['loved', 'it', 'friendly', 'servers', 'great', 'food', 'wonderful', 'and', 'imaginative', 'menu']
love friendli server great food wonder imagin menu
['the', 'heart', 'attack', 'grill', 'in', 'downtown', 'vegas', 'is', 'an', 'absolutely', 'flat', 'lined', 'excuse', 'for', 'a', 'restaurant']
heart attack grill downtown vega absolut flat line excus restaur
['not', 'much', 'seafood', 'and', 'like', 'strings', 'of', 'pasta', 'at', 'the', 'bottom']
much seafood like string pasta bottom
['the', 'salad', 'had', 'just', 'the', 'right', 'amount', 'of', 'sauce', 'to', 'not', 'over', 'power', 'the', 'scallop', 'which', 'was', 'perfectly', 'cooked']
salad right amount sauc power scallop perfectli cook
['the', 'ripped', 'banana', 'was', 'not', 'only', 'ripped', 'but', 'petrified', 'and', 'tasteless']
rip banana rip petrifi tasteless
['at', 'least', 'think', 'to', 'refill', 'my', 'water', 'before', 'i', 'struggle', 'to', 'wave', 'you', 'over', 'for', 'minutes']
least think refil water struggl wave minut
['this', 'place', 'receives', 'stars', 'for', 'their', 'appetizers']
place receiv star appet
['the', 'cocktails', 'are', 'all', 'handmade', 'and', 'delicious']
cocktail handmad delici
['we', 'd', 'definitely', 'go', 'back', 'here', 'again']
definit go back
['we', 'are', 'so', 'glad', 'we', 'found', 'this', 'place']
glad found place
['great', 'food', 'and', 'service', 'huge', 'portions', 'and', 'they', 'give', 'a', 'military', 'discount']
great food servic huge portion give militari discount
['always', 'a', 'great', 'time', 'at', 'dos', 'gringos']
alway great time do gringo
['update', 'went', 'back', 'for', 'a', 'second', 'time', 'and', 'it', 'was', 'still', 'just', 'as', 'amazing']
updat went back second time still amaz
['we', 'got', 'the', 'food', 'and', 'apparently', 'they', 'have', 'never', 'heard', 'of', 'salt', 'and', 'the', 'batter', 'on', 'the', 'fish', 'was', 'chewy']
got food appar never heard salt batter fish chewi
['a', 'great', 'way', 'to', 'finish', 'a', 'great']
great way finish great
['the', 'deal', 'included', 'tastings', 'and', 'drinks', 'and', 'jeff', 'went', 'above', 'and', 'beyond', 'what', 'we', 'expected']
deal includ tast drink jeff went beyond expect
['really', 'really', 'good', 'rice', 'all', 'the', 'time']
realli realli good rice time
['the', 'service', 'was', 'meh']
servic meh
['it', 'took', 'over', 'min', 'to', 'get', 'their', 'milkshake', 'which', 'was', 'nothing', 'more', 'than', 'chocolate', 'milk']
took min get milkshak noth chocol milk
['i', 'guess', 'i', 'should', 'have', 'known', 'that', 'this', 'place', 'would', 'suck', 'because', 'it', 'is', 'inside', 'of', 'the', 'excalibur', 'but', 'i', 'didn', 't', 'use', 'my', 'common', 'sense']
guess known place would suck insid excalibur use common sens
['the', 'scallop', 'dish', 'is', 'quite', 'appalling', 'for', 'value', 'as', 'well']
scallop dish quit appal valu well
['times', 'very', 'bad', 'customer', 'service']
time bad custom servic
['the', 'sweet', 'potato', 'fries', 'were', 'very', 'good', 'and', 'seasoned', 'well']
sweet potato fri good season well
['today', 'is', 'the', 'second', 'time', 'i', 've', 'been', 'to', 'their', 'lunch', 'buffet', 'and', 'it', 'was', 'pretty', 'good']
today second time lunch buffet pretti good
['there', 'is', 'so', 'much', 'good', 'food', 'in', 'vegas', 'that', 'i', 'feel', 'cheated', 'for', 'wasting', 'an', 'eating', 'opportunity', 'by', 'going', 'to', 'rice', 'and', 'company']
much good food vega feel cheat wast eat opportun go rice compani
['coming', 'here', 'is', 'like', 'experiencing', 'an', 'underwhelming', 'relationship', 'where', 'both', 'parties', 'can', 't', 'wait', 'for', 'the', 'other', 'person', 'to', 'ask', 'to', 'break', 'up']
come like experienc underwhelm relationship parti wait person ask break
['walked', 'in', 'and', 'the', 'place', 'smelled', 'like', 'an', 'old', 'grease', 'trap', 'and', 'only', 'others', 'there', 'eating']
walk place smell like old greas trap other eat
['the', 'turkey', 'and', 'roast', 'beef', 'were', 'bland']
turkey roast beef bland
['this', 'place', 'has', 'it']
place
['the', 'pan', 'cakes', 'everyone', 'are', 'raving', 'about', 'taste', 'like', 'a', 'sugary', 'disaster', 'tailored', 'to', 'the', 'palate', 'of', 'a', 'six', 'year', 'old']
pan cake everyon rave tast like sugari disast tailor palat six year old
['i', 'love', 'the', 'pho', 'and', 'the', 'spring', 'rolls', 'oh', 'so', 'yummy', 'you', 'have', 'to', 'try']
love pho spring roll oh yummi tri
['the', 'poor', 'batter', 'to', 'meat', 'ratio', 'made', 'the', 'chicken', 'tenders', 'very', 'unsatisfying']
poor batter meat ratio made chicken tender unsatisfi
['all', 'i', 'have', 'to', 'say', 'is', 'the', 'food', 'was', 'amazing']
say food amaz
['omelets', 'are', 'to', 'die', 'for']
omelet die
['everything', 'was', 'fresh', 'and', 'delicious']
everyth fresh delici
['in', 'summary', 'this', 'was', 'a', 'largely', 'disappointing', 'dining', 'experience']
summari larg disappoint dine experi
['it', 's', 'like', 'a', 'really', 'sexy', 'party', 'in', 'your', 'mouth', 'where', 'you', 're', 'outrageously', 'flirting', 'with', 'the', 'hottest', 'person', 'at', 'the', 'party']
like realli sexi parti mouth outrag flirt hottest person parti
['never', 'been', 'to', 'hard', 'rock', 'casino', 'before', 'will', 'never', 'ever', 'step', 'forward', 'in', 'it', 'again']
never hard rock casino never ever step forward
['best', 'breakfast', 'buffet']
best breakfast buffet
['say', 'bye', 'bye', 'to', 'your', 'tip', 'lady']
say bye bye tip ladi
['we', 'll', 'never', 'go', 'again']
never go
['will', 'be', 'back', 'again']
back
['food', 'arrived', 'quickly']
food arriv quickli
['it', 'was', 'not', 'good']
good
['on', 'the', 'up', 'side', 'their', 'cafe', 'serves', 'really', 'good', 'food']
side cafe serv realli good food
['our', 'server', 'was', 'fantastic', 'and', 'when', 'he', 'found', 'out', 'the', 'wife', 'loves', 'roasted', 'garlic', 'and', 'bone', 'marrow', 'he', 'added', 'extra', 'to', 'our', 'meal', 'and', 'another', 'marrow', 'to', 'go']
server fantast found wife love roast garlic bone marrow ad extra meal anoth marrow go
['the', 'only', 'good', 'thing', 'was', 'our', 'waiter', 'he', 'was', 'very', 'helpful', 'and', 'kept', 'the', 'bloddy', 'mary', 's', 'coming']
good thing waiter help kept bloddi mari come
['best', 'buffet', 'in', 'town', 'for', 'the', 'price', 'you', 'cannot', 'beat', 'it']
best buffet town price cannot beat
['i', 'loved', 'their', 'mussels', 'cooked', 'in', 'this', 'wine', 'reduction', 'the', 'duck', 'was', 'tender', 'and', 'their', 'potato', 'dishes', 'were', 'delicious']
love mussel cook wine reduct duck tender potato dish delici
['this', 'is', 'one', 'of', 'the', 'better', 'buffets', 'that', 'i', 'have', 'been', 'to']
one better buffet
['so', 'we', 'went', 'to', 'tigerlilly', 'and', 'had', 'a', 'fantastic', 'afternoon']
went tigerlilli fantast afternoon
['the', 'food', 'was', 'delicious', 'our', 'bartender', 'was', 'attentive', 'and', 'personable', 'and', 'we', 'got', 'a', 'great', 'deal']
food delici bartend attent person got great deal
['the', 'ambience', 'is', 'wonderful', 'and', 'there', 'is', 'music', 'playing']
ambienc wonder music play
['will', 'go', 'back', 'next', 'trip', 'out']
go back next trip
['sooooo', 'good']
sooooo good
['real', 'sushi', 'lovers', 'let', 's', 'be', 'honest', 'yama', 'is', 'not', 'that', 'good']
real sushi lover let honest yama good
['at', 'least', 'min', 'passed', 'in', 'between', 'us', 'ordering', 'and', 'the', 'food', 'arriving', 'and', 'it', 'wasn', 't', 'that', 'busy']
least min pass us order food arriv busi
['this', 'is', 'a', 'really', 'fantastic', 'thai', 'restaurant', 'which', 'is', 'definitely', 'worth', 'a', 'visit']
realli fantast thai restaur definit worth visit
['nice', 'spicy', 'and', 'tender']
nice spici tender
['good', 'prices']
good price
['check', 'it', 'out']
check
['it', 'was', 'pretty', 'gross']
pretti gross
['i', 've', 'had', 'better', 'atmosphere']
better atmospher
['kind', 'of', 'hard', 'to', 'mess', 'up', 'a', 'steak', 'but', 'they', 'did']
kind hard mess steak
['although', 'i', 'very', 'much', 'liked', 'the', 'look', 'and', 'sound', 'of', 'this', 'place', 'the', 'actual', 'experience', 'was', 'a', 'bit', 'disappointing']
although much like look sound place actual experi bit disappoint
['i', 'just', 'don', 't', 'know', 'how', 'this', 'place', 'managed', 'to', 'served', 'the', 'blandest', 'food', 'i', 'have', 'ever', 'eaten', 'when', 'they', 'are', 'preparing', 'indian', 'cuisine']
know place manag serv blandest food ever eaten prepar indian cuisin
['worst', 'service', 'to', 'boot', 'but', 'that', 'is', 'the', 'least', 'of', 'their', 'worries']
worst servic boot least worri
['service', 'was', 'fine', 'and', 'the', 'waitress', 'was', 'friendly']
servic fine waitress friendli
['the', 'guys', 'all', 'had', 'steaks', 'and', 'our', 'steak', 'loving', 'son', 'who', 'has', 'had', 'steak', 'at', 'the', 'best', 'and', 'worst', 'places', 'said', 'it', 'was', 'the', 'best', 'steak', 'he', 's', 'ever', 'eaten']
guy steak steak love son steak best worst place said best steak ever eaten
['we', 'thought', 'you', 'd', 'have', 'to', 'venture', 'further', 'away', 'to', 'get', 'good', 'sushi', 'but', 'this', 'place', 'really', 'hit', 'the', 'spot', 'that', 'night']
thought ventur away get good sushi place realli hit spot night
['host', 'staff', 'were', 'for', 'lack', 'of', 'a', 'better', 'word', 'bitches']
host staff lack better word bitch
['bland', 'not', 'a', 'liking', 'this', 'place', 'for', 'a', 'number', 'of', 'reasons', 'and', 'i', 'don', 't', 'want', 'to', 'waste', 'time', 'on', 'bad', 'reviewing', 'i', 'll', 'leave', 'it', 'at', 'that']
bland like place number reason want wast time bad review leav
['phenomenal', 'food', 'service', 'and', 'ambiance']
phenomen food servic ambianc
['i', 'wouldn', 't', 'return']
return
['definitely', 'worth', 'venturing', 'off', 'the', 'strip', 'for', 'the', 'pork', 'belly', 'will', 'return', 'next', 'time', 'i', 'm', 'in', 'vegas']
definit worth ventur strip pork belli return next time vega
['this', 'place', 'is', 'way', 'too', 'overpriced', 'for', 'mediocre', 'food']
place way overpr mediocr food
['penne', 'vodka', 'excellent']
penn vodka excel
['they', 'have', 'a', 'good', 'selection', 'of', 'food', 'including', 'a', 'massive', 'meatloaf', 'sandwich', 'a', 'crispy', 'chicken', 'wrap', 'a', 'delish', 'tuna', 'melt', 'and', 'some', 'tasty', 'burgers']
good select food includ massiv meatloaf sandwich crispi chicken wrap delish tuna melt tasti burger
['the', 'management', 'is', 'rude']
manag rude
['delicious', 'nyc', 'bagels', 'good', 'selections', 'of', 'cream', 'cheese', 'real', 'lox', 'with', 'capers', 'even']
delici nyc bagel good select cream chees real lox caper even
['great', 'subway', 'in', 'fact', 'it', 's', 'so', 'good', 'when', 'you', 'come', 'here', 'every', 'other', 'subway', 'will', 'not', 'meet', 'your', 'expectations']
great subway fact good come everi subway meet expect
['i', 'had', 'a', 'seriously', 'solid', 'breakfast', 'here']
serious solid breakfast
['this', 'is', 'one', 'of', 'the', 'best', 'bars', 'with', 'food', 'in', 'vegas']
one best bar food vega
['he', 'was', 'extremely', 'rude', 'and', 'really', 'there', 'are', 'so', 'many', 'other', 'restaurants', 'i', 'would', 'love', 'to', 'dine', 'at', 'during', 'a', 'weekend', 'in', 'vegas']
extrem rude realli mani restaur would love dine weekend vega
['my', 'drink', 'was', 'never', 'empty', 'and', 'he', 'made', 'some', 'really', 'great', 'menu', 'suggestions']
drink never empti made realli great menu suggest
['don', 't', 'do', 'it']

['the', 'waiter', 'wasn', 't', 'helpful', 'or', 'friendly', 'and', 'rarely', 'checked', 'on', 'us']
waiter help friendli rare check us
['my', 'husband', 'and', 'i', 'ate', 'lunch', 'here', 'and', 'were', 'very', 'disappointed', 'with', 'the', 'food', 'and', 'service']
husband ate lunch disappoint food servic
['and', 'the', 'red', 'curry', 'had', 'so', 'much', 'bamboo', 'shoots', 'and', 'wasn', 't', 'very', 'tasty', 'to', 'me']
red curri much bamboo shoot tasti
['nice', 'blanket', 'of', 'moz', 'over', 'top', 'but', 'i', 'feel', 'like', 'this', 'was', 'done', 'to', 'cover', 'up', 'the', 'subpar', 'food']
nice blanket moz top feel like done cover subpar food
['the', 'bathrooms', 'are', 'clean', 'and', 'the', 'place', 'itself', 'is', 'well', 'decorated']
bathroom clean place well decor
['the', 'menu', 'is', 'always', 'changing', 'food', 'quality', 'is', 'going', 'down', 'service', 'is', 'extremely', 'slow']
menu alway chang food qualiti go servic extrem slow
['the', 'service', 'was', 'a', 'little', 'slow', 'considering', 'that', 'were', 'served', 'by', 'people', 'servers', 'so', 'the', 'food', 'was', 'coming', 'in', 'a', 'slow', 'pace']
servic littl slow consid serv peopl server food come slow pace
['i', 'give', 'it', 'thumbs', 'down']
give thumb
['we', 'watched', 'our', 'waiter', 'pay', 'a', 'lot', 'more', 'attention', 'to', 'other', 'tables', 'and', 'ignore', 'us']
watch waiter pay lot attent tabl ignor us
['my', 'fianc', 'and', 'i', 'came', 'in', 'the', 'middle', 'of', 'the', 'day', 'and', 'we', 'were', 'greeted', 'and', 'seated', 'right', 'away']
fianc came middl day greet seat right away
['this', 'is', 'a', 'great', 'restaurant', 'at', 'the', 'mandalay', 'bay']
great restaur mandalay bay
['we', 'waited', 'for', 'forty', 'five', 'minutes', 'in', 'vain']
wait forti five minut vain
['crostini', 'that', 'came', 'with', 'the', 'salad', 'was', 'stale']
crostini came salad stale

In [ ]:
print(review)
print(corpus)

overal great experi

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(binary = True, max_features=1420)
x = cv.fit_transform(corpus)
#x[0].toarray()
x

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4771 stored elements and shape (900, 1420)>

In [ ]:
y = a1['Liked']
y = a1.iloc[:, -1].values
y

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1])

In [ ]:
import pickle
bow_path = 'c1.pkl'
pickle.dump(cv, open(bow_path, 'wb'))

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [ ]:
from sklearn.naive_bayes import MultinomialNB #2nd type gaussian
reviews_n_liked = MultinomialNB().fit(x_train, y_train)

In [ ]:
y_pred = reviews_n_liked.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

score = accuracy_score(y_test, y_pred)
print(score)

cm = confusion_matrix(y_test, y_pred)
print(cm)

cr = classification_report(y_test, y_pred)
print(cr)

0.7388888888888889
[[51 27]
 [20 82]]
              precision    recall  f1-score   support

           0       0.72      0.65      0.68        78
           1       0.75      0.80      0.78       102

    accuracy                           0.74       180
   macro avg       0.74      0.73      0.73       180
weighted avg       0.74      0.74      0.74       180

In [ ]:
#kappa Score
from sklearn.metrics import cohen_kappa_score
print("Kappa Score:", cohen_kappa_score(y_test, y_pred))

Kappa Score: 0.46265243902439024

In [ ]:
import joblib
joblib.dump(reviews_n_liked, 'c2_reviews_n_liked_model')

['c2_reviews_n_liked_model']

In [ ]:
a1['TextBlob_Prediction'] = a1['TextBlob_Sentiment'].map({
    'Positive': 1,
    'Negative': 0,
    'Neutral': 0
})

In [ ]:
from sklearn.metrics import accuracy_score

textblob_accuracy = accuracy_score(
    a1['Liked'],
    a1['TextBlob_Prediction']
)

print("TextBlob Accuracy:", textblob_accuracy)

TextBlob Accuracy: 0.7755555555555556

In [ ]:
a1['VADER_Prediction'] = a1['VADER_Sentiment'].map({
    'Positive': 1,
    'Negative': 0,
    'Neutral': 0
})

vader_accuracy = accuracy_score(
    a1['Liked'],
    a1['VADER_Prediction']
)

print("VADER Accuracy:", vader_accuracy)

VADER Accuracy: 0.8133333333333334

In [ ]:
a1['HF_Prediction'] = a1['HF_Sentiment'].map({
    'POSITIVE': 1,
    'NEGATIVE': 0
})

hf_accuracy = accuracy_score(
    a1['Liked'],
    a1['HF_Prediction']
)

print("Hugging Face Accuracy:", hf_accuracy)

Hugging Face Accuracy: 0.9244444444444444

In [ ]:
print("TextBlob Accuracy:", textblob_accuracy)
print("VADER Accuracy:", vader_accuracy)
print("Hugging Face Accuracy:", hf_accuracy)

TextBlob Accuracy: 0.7755555555555556
VADER Accuracy: 0.8133333333333334
Hugging Face Accuracy: 0.9244444444444444